import Foundation
import XCTest
@testable import OrbitCore

final class PhysicsTests: XCTestCase {
    /// Values were generated by the unmodified browser physics.js, not by this port.
    private func reference() throws -> Reference {
        let url = try XCTUnwrap(Bundle.module.url(forResource: "reference", withExtension: "json"))
        return try JSONDecoder().decode(Reference.self, from: Data(contentsOf: url))
    }

    func testAllTwentyOriginalSolutionsRemainLegalAndWin() throws {
        let levels = LevelCatalog.all
        XCTAssertEqual(levels.count, 20)
        for sample in try reference().terminal {
            let level = levels[sample.levelIndex]
            var placed: [Hole] = []
            for hole in level.answer {
                let capacity = Physics.capacityAt(level: level, holes: placed, x: hole.x, y: hole.y)
                XCTAssertGreaterThanOrEqual(capacity + 1e-9, hole.mass, level.name)
                placed.append(hole)
            }
            let result = Physics.fly(level: level, holes: level.answer)
            XCTAssertEqual(result.status, .won, level.name)
            compare(result, to: sample.expected, context: level.name)
        }
    }

    func testIntermediateFlightsMatchJavaScriptReference() throws {
        for sample in try reference().samples {
            let level = LevelCatalog.all[sample.levelIndex]
            var flight = Physics.launch(level: level)
            for _ in 0..<sample.steps { Physics.step(level: level, holes: level.answer, flight: &flight) }
            compare(flight, to: sample.expected, context: "\(level.name), \(sample.steps) steps")
        }
    }

    func testPlacementCapacityMatchesJavaScriptReference() throws {
        for probe in try reference().capacities {
            let level = LevelCatalog.all[probe.levelIndex]
            let capacity = Physics.capacityAt(level: level, holes: [], x: probe.x, y: probe.y)
            // Original threshold was 8; geometry above it remains byte-for-byte compatible.
            let originalThresholdCapacity = capacity >= 8 - 1e-9 ? capacity : 0
            XCTAssertEqual(originalThresholdCapacity, probe.expected, accuracy: 1e-8, "\(level.name) at \(probe.x), \(probe.y)")
        }
    }

    func testPortalsKeepVelocityAndRemainLockedUntilShipLeavesExit() {
        let level = example(bodies: [
            Body(type: .wormhole, x: 200, y: 450, r: 26, id: "a", twin: "b"),
            Body(type: .wormhole, x: 1100, y: 450, r: 26, id: "b", twin: "a")
        ])
        var flight = Physics.launch(level: level)
        let velocity = flight.velocity
        Physics.step(level: level, holes: [], flight: &flight)
        XCTAssertEqual(flight.position, Vec2(x: 1100, y: 450))
        XCTAssertEqual(flight.velocity, velocity)
        XCTAssertEqual(flight.portal, "b")
        XCTAssertEqual(flight.jumped?.from.id, "a")
        XCTAssertEqual(flight.jumped?.to.id, "b")
        XCTAssertEqual(flight.jumps, 1)
        XCTAssertEqual(flight.time, Physics.stepDuration)

        Physics.step(level: level, holes: [], flight: &flight)
        XCTAssertEqual(flight.jumps, 1)
        XCTAssertNil(flight.jumped)
        for _ in 0..<70 { Physics.step(level: level, holes: [], flight: &flight) }
        XCTAssertNil(flight.portal)
        flight.x = 1100
        Physics.step(level: level, holes: [], flight: &flight)
        XCTAssertEqual(flight.position, Vec2(x: 200, y: 450))
        XCTAssertEqual(flight.jumps, 2)
    }

    func testStationDoesNotAcceptShipUntilEveryBeaconIsPassed() {
        let level = Level(name: "Beacon gate", matter: 40,
                          ship: Ship(x: 200, y: 450, speed: 240),
                          goal: Goal(x: 204, y: 450, r: 4),
                          beacons: [Beacon(x: 220, y: 450, r: 4)])
        var flight = Physics.launch(level: level)
        Physics.step(level: level, holes: [], flight: &flight)
        XCTAssertEqual(flight.status, .flying)
        XCTAssertEqual(flight.left, 1)
        for _ in 0..<16 { Physics.step(level: level, holes: [], flight: &flight) }
        XCTAssertEqual(flight.passed, [true])
        XCTAssertEqual(flight.left, 0)
        XCTAssertEqual(flight.reached, level.beacons[0])
        XCTAssertEqual(flight.status, .flying)
        flight.x = 203
        Physics.step(level: level, holes: [], flight: &flight)
        XCTAssertEqual(flight.status, .won)
    }

    func testOverlappingBeaconsAreCollectedOnePerStepInOriginalOrder() {
        let beacon = Beacon(x: 200, y: 450, r: 30)
        var level = example()
        level.beacons = [beacon, beacon]
        var flight = Physics.launch(level: level)
        Physics.step(level: level, holes: [], flight: &flight)
        XCTAssertEqual(flight.passed, [true, false])
        XCTAssertEqual(flight.left, 1)
        XCTAssertTrue(flight.closest.isInfinite)
        Physics.step(level: level, holes: [], flight: &flight)
        XCTAssertEqual(flight.passed, [true, true])
        XCTAssertEqual(flight.left, 0)
    }

    func testCollisionChecksUseHorizonAndShipRadiusBeforeIntegration() {
        for kind in [BodyType.planet, .repulsor, .asteroid] {
            let level = example(bodies: [Body(type: kind, x: 230, y: 450, r: 24, mass: 30)])
            var flight = Physics.launch(level: level)
            Physics.step(level: level, holes: [], flight: &flight)
            XCTAssertEqual(flight.status, .crashed)
            XCTAssertEqual(flight.time, 0)
            XCTAssertEqual(flight.cause, .body(level.bodies[0]))
            let ended = flight
            Physics.step(level: level, holes: [], flight: &flight)
            XCTAssertEqual(flight, ended)
        }
        let level = example()
        let hole = Hole(x: 200, y: 450, mass: 8)
        var flight = Physics.launch(level: level)
        Physics.step(level: level, holes: [hole], flight: &flight)
        XCTAssertEqual(flight.status, .imploded)
        XCTAssertEqual(flight.cause, .playerHole(hole))
    }

    func testRepulsorsReverseGravityWithoutChangingMagnitude() {
        let planet = example(bodies: [Body(type: .planet, x: 800, y: 450, r: 20, mass: 55)])
        let repulsor = example(bodies: [Body(type: .repulsor, x: 800, y: 450, r: 20, mass: 55)])
        let inward = Physics.pullAt(level: planet, holes: [], x: 200, y: 450, time: 0)
        let outward = Physics.pullAt(level: repulsor, holes: [], x: 200, y: 450, time: 0)
        XCTAssertGreaterThan(inward.x, 0)
        XCTAssertEqual(inward.x, -outward.x)
        XCTAssertEqual(inward.y, 0)
        XCTAssertEqual(outward.y, 0)
    }

    func testBecalmedShipStrandsButExternalGravityStartsIt() {
        let level = LevelCatalog.all[10]
        XCTAssertTrue(Physics.becalmed(level: level, holes: []))
        XCTAssertFalse(Physics.becalmed(level: level, holes: level.answer))
        XCTAssertFalse(Physics.becalmed(level: LevelCatalog.all[17], holes: []))
        let result = Physics.fly(level: level, holes: [])
        XCTAssertEqual(result.status, .stranded)
        XCTAssertEqual(result.position, level.ship.position)
        XCTAssertGreaterThan(result.time, Physics.flightLimit)
    }

    func testShipBeyondWorldMarginIsLost() {
        let level = Level(name: "Exit", matter: 0,
                          ship: Ship(x: 1839.5, y: 450, speed: 240),
                          goal: Goal(x: 200, y: 450, r: 20))
        var flight = Physics.launch(level: level)
        Physics.step(level: level, holes: [], flight: &flight)
        XCTAssertEqual(flight.status, .lost)
    }

    func testCapacityRejectsBoundsShipGoalBeaconZonesAndOtherHoles() {
        var level = example()
        level.beacons = [Beacon(x: 800, y: 200, r: 30)]
        level.zones = [Zone(x: 600, y: 500, w: 300, h: 200)]
        let existing = Hole(x: 500, y: 400, mass: 8)
        let blocked = [Vec2(x: -1, y: 50), Vec2(x: 5, y: 450), level.ship.position,
                       level.goal.position, level.beacons[0].position, Vec2(x: 700, y: 600), existing.position]
        for point in blocked {
            XCTAssertEqual(Physics.capacityAt(level: level, holes: [existing], x: point.x, y: point.y), 0)
        }
        XCTAssertGreaterThan(Physics.capacityAt(level: level, holes: [], x: 1000, y: 100), 0)
    }

    func testCapacityHonorsMatterAndHoleLimitWhenResizing() {
        var level = example()
        level.matter = 40
        let existing = Hole(x: 500, y: 200, mass: 35)
        XCTAssertEqual(Physics.capacityAt(level: level, holes: [existing], x: 1000, y: 200), 5)
        level.limit = 1
        XCTAssertEqual(Physics.capacityAt(level: level, holes: [existing], x: 1000, y: 200), 0)
        XCTAssertEqual(Physics.capacityAt(level: level, holes: [], x: existing.x, y: existing.y), 40)
    }

    func testMovingBodiesAndStationPositionsUseOriginalClock() {
        let body = Body(type: .asteroid, x: 100, y: 100, r: 10,
                        orbit: OrbitMotion(cx: 800, cy: 450, radius: 100, period: 4))
        let at = Physics.bodyAt(body: body, time: 1)
        XCTAssertEqual(at.x, 800, accuracy: 1e-10)
        XCTAssertEqual(at.y, 550, accuracy: 1e-10)
        let patrol = Body(type: .asteroid, x: 100, y: 100, r: 10,
                          patrol: PatrolMotion(x: 500, y: 300, period: 4))
        XCTAssertEqual(Physics.bodyAt(body: patrol, time: 2), Vec2(x: 500, y: 300))
        let level = LevelCatalog.all[14]
        let goal = Physics.goalAt(level: level, time: 2)
        XCTAssertEqual(goal.x, 1100, accuracy: 1e-10)
        XCTAssertEqual(goal.y, 620, accuracy: 1e-10)
    }

    func testHoleCodableRetainsIdentityAndLevelCatalogRoundTrips() throws {
        let hole = Hole(x: 700, y: 100, mass: 21)
        XCTAssertEqual(try JSONDecoder().decode(Hole.self, from: JSONEncoder().encode(hole)), hole)
        let levels = LevelCatalog.all
        XCTAssertEqual(try JSONDecoder().decode([Level].self, from: JSONEncoder().encode(levels)), levels)
    }

    private func example(bodies: [Body] = []) -> Level {
        Level(name: "Test", matter: 80, ship: Ship(x: 200, y: 450, speed: 100),
              goal: Goal(x: 1400, y: 800, r: 36), bodies: bodies)
    }

    private func compare(_ flight: Flight, to expected: Snapshot, context: String,
                         file: StaticString = #filePath, line: UInt = #line) {
        // Cross-platform libm can differ in the final bits of sin/cos. This is
        // sub-millionth-world-unit tolerance, far below one rendered pixel.
        XCTAssertEqual(flight.time, expected.time, accuracy: 1e-9, context, file: file, line: line)
        XCTAssertEqual(flight.x, expected.x, accuracy: 1e-6, context, file: file, line: line)
        XCTAssertEqual(flight.y, expected.y, accuracy: 1e-6, context, file: file, line: line)
        XCTAssertEqual(flight.vx, expected.vx, accuracy: 1e-6, context, file: file, line: line)
        XCTAssertEqual(flight.vy, expected.vy, accuracy: 1e-6, context, file: file, line: line)
        XCTAssertEqual(flight.status.rawValue, expected.status, context, file: file, line: line)
        XCTAssertEqual(flight.passed, expected.passed, context, file: file, line: line)
        XCTAssertEqual(flight.left, expected.left, context, file: file, line: line)
        XCTAssertEqual(flight.portal, expected.portal, context, file: file, line: line)
        XCTAssertEqual(flight.jumps, expected.jumps, context, file: file, line: line)
        if let closest = expected.closest {
            XCTAssertEqual(flight.closest, closest, accuracy: 1e-6, context, file: file, line: line)
        } else {
            XCTAssertTrue(flight.closest.isInfinite, context, file: file, line: line)
        }
    }
}

private struct Reference: Decodable {
    var terminal: [Terminal]
    var samples: [Sample]
    var capacities: [Capacity]
}
private struct Terminal: Decodable { var levelIndex: Int; var expected: Snapshot }
private struct Sample: Decodable { var levelIndex: Int; var steps: Int; var expected: Snapshot }
private struct Capacity: Decodable { var levelIndex: Int; var x: Double; var y: Double; var expected: Double }
private struct Snapshot: Decodable {
    var time: Double; var x: Double; var y: Double; var vx: Double; var vy: Double
    var status: String; var passed: [Bool]; var left: Int; var portal: String?; var jumps: Int; var closest: Double?
}
